---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moe
spec:
  replicas: {{.Values.scale}}
  selector:
    matchLabels:
      app: moe
  template:
    metadata:
      labels:
        app: moe
    spec:
      containers:
        - image: moe:{{.Values.currentVersion}}
          imagePullPolicy: Never
          name: moe
          env:
          - name: CURRENT_VERSION
            value: {{.Values.currentVersion}}
          ports:
            -
              containerPort: {{.Values.containerPort}}