---
apiVersion: v1
kind: Pod
metadata:
  name: feelingtracker
  labels:
    app: feelingtracker
spec:
  containers:
    - name: feelingtracker
      image: "feelingtracker:v1"
      imagePullPolicy: Never
      env:
        - name: CURRENT_VERSION
          value: v1
      ports:
        - containerPort: 3000