---
apiVersion: v1
kind: Pod
metadata:
  name: simplepod
  labels:
    app: simplepod
spec:
  containers:
  - name: simplepod
    image: busybox
    ports:
      - name: app
        containerPort: 8080
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    env:
      - name: CURRENT_EXERCISE_VERSION
        value: v1
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
#to check in out type, kubectl exec -it simplepod -n default env
