---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
    name: simple-replicaset
spec:
    replicas: 3
    selector:
       matchLabels:
          app: simpleapp
    template:
       metadata:
          labels:
             app: simpleapp
             env: test
       spec:
         containers:
           - name: simplepod
             image: busybox
             command: ['sh', '-c', 'echo Hello Kubernetes from SimplePod! && sleep 3600']
             env:
               - name: CURRENT_EXERCISE
                 value: replicaset
#to check in out type, kubectl get replicaset
# try to delete a pod, kubectl get pod
