---
apiVersion: v1
kind: Pod
metadata:
  name: unhealthypod
  labels:
    app: unhealthypod
spec:
  containers:
  - name: unhealthypod
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
#to check in out type, kubectl exec -it simplepod -n default env
