---
apiVersion: v1
kind: Pod
metadata:
  name: unhealthypod
spec:
  containers:
  - name: unhealthypod
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5