---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stickyreaderwriter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stickyreaderwriter
  template:
    metadata:
      labels:
        app: stickyreaderwriter
    spec:
      volumes:
        - name: reselbob-pv-storage
          persistentVolumeClaim:
           claimName: reselbob-pv-claim
      containers:
        - name: stickyreaderwriter
          image: stickyreaderwriter:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8112
              name: "http-server"
          volumeMounts:
            - mountPath: "/mydata"
              name: reselbob-pv-storage