---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: simpleapp
spec:
  containers:
  - name: simple-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    env:
      - name: CURRENT_EXERCISE_VERSION
        value: v1
#to check in out type, kubectl exec -it myapp-pod -n default env
