---
spec:
  selector:
    matchLabels:
      app: simpleapi
  template:
    metadata:
      labels:
        app: simpleapi
    spec:
      containers:
        - image: "simpleapi:v2"
          imagePullPolicy: Never
          name: simpleapi
          env:
          - name: CURRENT_VERSION
            value: v2
          ports:
            -
              containerPort: 8113