---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: simpleapi
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: simpleapi
   template:
     metadata:
       labels:
         app: simpleapi
     spec:
       containers:
         - name: simpleapi
           image: simpleapi:v1
           imagePullPolicy: Never
           env:
             name: CURRENT_VERSION
             value: "v1"
           ports:
             - containerPort: 8113