---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: feelingtrackeringress
  annotations:
    http.port: "443"
spec:
  backend:
    serviceName: /feelingtracker
    servicePort: 3000
  rules:
  - host:
    http:
      paths:
      - path: /feelingtracker
        backend:
          serviceName: feelingtracker
          servicePort: 3000