---
kind: Service
apiVersion: v1
metadata:
  name: feelingtracker
spec:
  selector:
    app: feelingtracker
  type: "LoadBalancer"
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: 3000

