---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test
  name: devs-read-pods
subjects:
  - kind: Group
    name: devs
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: dicktracy #name is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-access
  apiGroup: rbac.authorization.k8s.io

