---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stooges-ingress
spec:
  backend:
    serviceName: stooges
    servicePort: 8130
  rules:
  - host:
    http:
      paths:
      - path: /moe
        backend:
          serviceName: moe
          servicePort: 8130
      - path: /larry
        backend:
          serviceName: larry
          servicePort: 8130
      - path: /curly
        backend:
          serviceName: curly
          servicePort: 8130